"use strict";
exports.__esModule = true;
var exercicio1_1 = require("./exercicio1");
var exercicio2_1 = require("./exercicio2");
var exercicio3_1 = require("./exercicio3");
console.log("Exercício 1");
exercicio1_1.numbers.print();
exercicio1_1.numbers.appendToTail(5);
exercicio1_1.numbers.print();
console.log("Exercício 2");
console.log(exercicio2_1.firstNode.isEmpty());
exercicio2_1.firstNode.push(1);
exercicio2_1.firstNode.push(2);
exercicio2_1.firstNode.pop();
exercicio2_1.firstNode.print();
console.log(exercicio2_1.firstNode.isEmpty());
console.log("Exercício 3");
console.log(exercicio3_1.queue.isEmpty());
exercicio3_1.queue.print();
exercicio3_1.queue.enqueue(6);
exercicio3_1.queue.print();
exercicio3_1.queue.dequeue();
exercicio3_1.queue.print();
